import json
import subprocess
import sys
import tempfile
import unittest
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parents[1]
SCRIPT = REPO_ROOT / "scripts" / "generate-manufacturing-report.py"


class ManufacturingReportTests(unittest.TestCase):
    def test_repo_includes_bambu_profile_directories(self):
        repo_root = REPO_ROOT
        for relative_path in ("profiles/machine", "profiles/process", "profiles/filament"):
            self.assertTrue((repo_root / relative_path).is_dir(), f"Missing required Bambu profile directory: {relative_path}")

    def test_generate_report_parses_basic_gcode_metadata(self):
        gcode_content = """; generated by PrusaSlicer 2.9.6
; estimated printing time (normal mode) = 1h 23m
; filament used [mm] = 202.63
; filament used [cm3] = 10.4
; filament used [g] = 12.1
; layer_count = 123
; nozzle_diameter = 0.4
; printer_model = Home FDM
; material = Generic PLA
; total layers = 123
"""

        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            gcode_path = tmpdir_path / "sample.gcode"
            report_path = tmpdir_path / "report.json"
            gcode_path.write_text(gcode_content, encoding="utf-8")

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--input",
                    str(gcode_path),
                    "--output",
                    str(report_path),
                ],
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, msg=result.stderr)
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertGreaterEqual(payload["print_time_minutes"], 83)
            self.assertAlmostEqual(payload["filament_mm"], 202.63)
            self.assertAlmostEqual(payload["filament_g"], 12.1)
            self.assertEqual(payload["layer_count"], 123)
            self.assertEqual(payload["printer_model"], "Home FDM")

    def test_generate_report_parses_bambu_studio_metadata(self):
        gcode_content = """; generated by Bambu Studio 02.08.01.55
;TIME_ELAPSED = 1h 23m 45s
;LAYER_COUNT = 123
;NOZZLE_DIAMETER = 0.4
;PRINTER_MODEL = X1C
;MATERIAL = PLA Basic
;FILAMENT_USED_MM = 202.63
;FILAMENT_USED_CM3 = 10.4
;FILAMENT_USED_G = 12.1
"""

        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            gcode_path = tmpdir_path / "sample_bambu.gcode"
            report_path = tmpdir_path / "report_bambu.json"
            gcode_path.write_text(gcode_content, encoding="utf-8")

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--input",
                    str(gcode_path),
                    "--output",
                    str(report_path),
                ],
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, msg=result.stderr)
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertGreaterEqual(payload["print_time_minutes"], 83)
            self.assertAlmostEqual(payload["filament_mm"], 202.63)
            self.assertAlmostEqual(payload["filament_g"], 12.1)
            self.assertEqual(payload["layer_count"], 123)
            self.assertEqual(payload["printer_model"], "X1C")
            self.assertEqual(payload["material"], "PLA Basic")

    def test_generate_report_parses_real_bambu_gcode_header(self):
        gcode_content = """; HEADER_BLOCK_START
; BambuStudio 02.08.01.55
; estimated printing time (normal mode) = 4h 40m 21s
; total layer number: 155
; interlocking_beam_layer_count = 2
; total filament length [mm] : 13336.93
; total filament volume [cm^3] : 32079.08
; total filament weight [g] : 0.00
; filament_diameter: 1.75
; filament_type = PLA
; nozzle_diameter = 0.4
; printer_model =
; filament: 1
; HEADER_BLOCK_END
"""

        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            gcode_path = tmpdir_path / "real_bambu.gcode"
            report_path = tmpdir_path / "real_bambu_report.json"
            gcode_path.write_text(gcode_content, encoding="utf-8")

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--input",
                    str(gcode_path),
                    "--output",
                    str(report_path),
                ],
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, msg=result.stderr)
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["print_time_minutes"], 280)
            self.assertAlmostEqual(payload["filament_mm"], 13336.93)
            self.assertAlmostEqual(payload["filament_cm3"], 32079.08)
            self.assertAlmostEqual(payload["filament_g"], 0.0)
            self.assertEqual(payload["layer_count"], 155)
            self.assertEqual(payload["material"], "PLA")
            self.assertAlmostEqual(payload["nozzle_diameter"], 0.4)
            self.assertIsNone(payload["printer_model"])

    def test_generate_report_parses_bambu_3mf_metadata(self):
        with tempfile.TemporaryDirectory() as tmpdir:
            tmpdir_path = Path(tmpdir)
            three_mf_path = tmpdir_path / "sample.3mf"
            report_path = tmpdir_path / "report_3mf.json"

            model_xml = """<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<model unit=\"millimeter\" xml:lang=\"en-US\">
  <metadata name=\"PrintTime\">4h 40m 21s</metadata>
  <metadata name=\"LayerCount\">155</metadata>
  <metadata name=\"NozzleDiameter\">0.4</metadata>
  <metadata name=\"PrinterModel\">X1C</metadata>
  <metadata name=\"Material\">PLA</metadata>
  <metadata name=\"FilamentLength\">13336.93</metadata>
  <metadata name=\"FilamentVolume\">32079.08</metadata>
  <metadata name=\"FilamentWeight\">0.00</metadata>
</model>
"""

            import zipfile
            with zipfile.ZipFile(three_mf_path, "w", compression=zipfile.ZIP_DEFLATED) as zf:
                zf.writestr("3D/3dmodel.model", model_xml)

            result = subprocess.run(
                [
                    sys.executable,
                    str(SCRIPT),
                    "--input",
                    str(three_mf_path),
                    "--output",
                    str(report_path),
                ],
                capture_output=True,
                text=True,
            )

            self.assertEqual(result.returncode, 0, msg=result.stderr)
            payload = json.loads(report_path.read_text(encoding="utf-8"))
            self.assertEqual(payload["print_time_minutes"], 280)
            self.assertAlmostEqual(payload["filament_mm"], 13336.93)
            self.assertAlmostEqual(payload["filament_cm3"], 32079.08)
            self.assertAlmostEqual(payload["filament_g"], 0.0)
            self.assertEqual(payload["layer_count"], 155)
            self.assertEqual(payload["material"], "PLA")
            self.assertEqual(payload["printer_model"], "X1C")
            self.assertAlmostEqual(payload["nozzle_diameter"], 0.4)
